project:
  type: website
  output-dir: docs

website:
  title: ""
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://catterson.github.io/ystats/
        text: Why Statistics?
    pinned: true
    collapse: false
format:
  html:
    theme: lux
    toc: true
    reference-location: margin
    citation-location: margin
